<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DownTrack.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="CliWrap" />
    <ProjectReference Include="..\DownTrack.Application\DownTrack.Application.csproj" />
  </ItemGroup>
</Project>
