<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <AssemblyName>MediaForge</AssemblyName>
    <RootNamespace>MediaForge.App</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MediaForge.Core\MediaForge.Core.csproj" />
    <ProjectReference Include="..\MediaForge.Application\MediaForge.Application.csproj" />
    <ProjectReference Include="..\MediaForge.Infrastructure\MediaForge.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\MediaForge.png"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
